// ═══════════════════════════════════════════════════════════════
// Shared Dataverse Entity Types
// Mesa de Ayuda de Mantenimiento – Zamorano University
// These types mirror the Dataverse table schemas.
// In production, model files are auto-generated by:
//   pac code add-data-source -a dataverse -t <table-logical-name>
// ═══════════════════════════════════════════════════════════════

// ─── Choice Enums ────────────────────────────────────────────

export enum TicketPriority {
    Low = 100000000,
    Medium = 100000001,
    High = 100000002,
    Critical = 100000003,
}

export const ticketPriorityLabels: Record<TicketPriority, string> = {
    [TicketPriority.Low]: "Baja",
    [TicketPriority.Medium]: "Media",
    [TicketPriority.High]: "Alta",
    [TicketPriority.Critical]: "Crítica",
};

export const ticketPriorityColors: Record<TicketPriority, string> = {
    [TicketPriority.Low]: "#4CAF50",
    [TicketPriority.Medium]: "#FF9800",
    [TicketPriority.High]: "#F44336",
    [TicketPriority.Critical]: "#9C27B0",
};

export enum TicketStatus {
    New = 100000000,
    Assigned = 100000001,
    InDiagnosis = 100000002,
    OnHold = 100000003,
    InProgress = 100000004,
    Resolved = 100000005,
    Closed = 100000006,
    Cancelled = 100000007,
}

export const ticketStatusLabels: Record<TicketStatus, string> = {
    [TicketStatus.New]: "Nuevo",
    [TicketStatus.Assigned]: "Asignado",
    [TicketStatus.InDiagnosis]: "En Diagnóstico",
    [TicketStatus.OnHold]: "En Espera",
    [TicketStatus.InProgress]: "En Progreso",
    [TicketStatus.Resolved]: "Resuelto",
    [TicketStatus.Closed]: "Cerrado",
    [TicketStatus.Cancelled]: "Cancelado",
};

export const ticketStatusColors: Record<TicketStatus, string> = {
    [TicketStatus.New]: "#2196F3",
    [TicketStatus.Assigned]: "#03A9F4",
    [TicketStatus.InDiagnosis]: "#00BCD4",
    [TicketStatus.OnHold]: "#FF9800",
    [TicketStatus.InProgress]: "#8BC34A",
    [TicketStatus.Resolved]: "#4CAF50",
    [TicketStatus.Closed]: "#9E9E9E",
    [TicketStatus.Cancelled]: "#78909C",
};

export enum MaterialRequestStatus {
    Required = 100000000,
    PendingApproval = 100000001,
    Approved = 100000002,
    Rejected = 100000003,
    Delivered = 100000004,
    Consumed = 100000005,
}

export const materialRequestStatusLabels: Record<MaterialRequestStatus, string> = {
    [MaterialRequestStatus.Required]: "Requerido",
    [MaterialRequestStatus.PendingApproval]: "Pendiente Aprobación",
    [MaterialRequestStatus.Approved]: "Aprobado",
    [MaterialRequestStatus.Rejected]: "Rechazado",
    [MaterialRequestStatus.Delivered]: "Entregado",
    [MaterialRequestStatus.Consumed]: "Consumido",
};

export enum SatisfactionRating {
    VeryDissatisfied = 1,
    Dissatisfied = 2,
    Neutral = 3,
    Satisfied = 4,
    VerySatisfied = 5,
}

// ─── Entity Interfaces ──────────────────────────────────────

export interface Department {
    cr_departmentid: string;
    cr_department_id: string; // autonumber display
    cr_name: string;
    cr_is_active: boolean;
}

export interface Location {
    cr_locationid: string;
    cr_location_id: string;
    cr_campus: string;
    cr_building: string;
    cr_floor?: string;
    cr_room?: string;
    cr_full_path: string;
    cr_is_active: boolean;
}

export interface Category {
    cr_categoryid: string;
    cr_category_id: string;
    cr_name: string;
    cr_department: string;           // lookup id
    cr_default_sla_policy?: string;  // lookup id
    cr_requires_evidence: boolean;
    cr_is_active: boolean;
}

export interface Subcategory {
    cr_subcategoryid: string;
    cr_subcategory_id: string;
    cr_category_id: string;  // lookup id
    cr_name: string;
    cr_default_assigned_team?: string;
    cr_is_active: boolean;
}

export interface Ticket {
    cr_ticketid: string;
    cr_ticket_id: string;   // autonumber display e.g. TKT-000001
    cr_title: string;
    cr_description: string;
    cr_requesting_department: string;
    cr_requesting_user: string;
    cr_location_id: string;
    cr_category_id: string;
    cr_subcategory_id?: string;
    cr_priority: TicketPriority;
    cr_status: TicketStatus;
    cr_is_emergency: boolean;
    cr_assigned_to?: string;
    cr_assigned_team?: string;
    createdon: string;   // ISO datetime
    cr_first_response_date?: string;
    cr_resolved_date?: string;
    cr_closed_date?: string;
    cr_sla_instance_id?: string;
    cr_related_asset_id?: string;
    cr_on_hold_reason?: string;
    cr_on_hold_eta?: string;
    // Expanded navigation properties (when $expand is used)
    _cr_requesting_department_value?: string;
    _cr_category_id_value?: string;
    _cr_location_id_value?: string;
    _cr_assigned_to_value?: string;
}

export interface WorkOrder {
    cr_workorderid: string;
    cr_workorder_id: string;
    cr_ticket_id: string;
    cr_assigned_technician?: string;
    cr_status: TicketStatus;
    cr_preliminary_diagnosis?: string;
    cr_root_cause?: string;
    cr_solution_applied?: string;
    cr_work_checklist?: string;
    cr_before_evidence?: string;
    cr_after_evidence?: string;
    cr_estimated_labor_hours?: number;
    cr_actual_labor_hours?: number;
    cr_estimated_material_cost?: number;
    cr_actual_material_cost?: number;
    cr_estimated_external_cost?: number;
    cr_actual_external_cost?: number;
    cr_start_date?: string;
    cr_completion_date?: string;
    cr_total_estimated_cost?: number;
    cr_total_actual_cost?: number;
    cr_cost_variance?: number;
}

export interface SLAPolicy {
    cr_sla_policyid: string;
    cr_sla_policy_id: string;
    cr_name: string;
    cr_priority: TicketPriority;
    cr_service_type?: string;
    cr_department?: string;
    cr_first_response_minutes: number;
    cr_diagnosis_time_hours: number;
    cr_resolution_time_hours: number;
    cr_is_active: boolean;
}

export interface SLAInstance {
    cr_sla_instanceid: string;
    cr_sla_instance_id: string;
    cr_ticket_id: string;
    cr_sla_policy_id: string;
    cr_first_response_deadline: string;
    cr_diagnosis_deadline: string;
    cr_resolution_deadline: string;
    cr_first_response_met: boolean;
    cr_diagnosis_met: boolean;
    cr_resolution_met: boolean;
    cr_overall_sla_met: boolean;
    cr_breach_reason?: string;
    cr_is_paused: boolean;
    cr_paused_at?: string;
    cr_total_paused_minutes: number;
}

export interface MaterialRequest {
    cr_material_requestid: string;
    cr_material_request_id: string;
    cr_ticket_id: string;
    cr_workorder_id?: string;
    cr_requested_by: string;
    cr_status: MaterialRequestStatus;
    cr_material_description: string;
    cr_estimated_cost: number;
    cr_justification: string;
    cr_approved_by?: string;
    cr_approval_date?: string;
    cr_delivered_date?: string;
    cr_rejection_reason?: string;
}

export interface TimeLog {
    cr_timelogid: string;
    cr_timelog_id: string;
    cr_workorder_id: string;
    cr_technician: string;
    cr_start_time: string;
    cr_end_time?: string;
    cr_duration_hours?: number;
    cr_activity_description: string;
    cr_is_active: boolean;
}

export interface Asset {
    cr_assetid: string;
    cr_asset_id: string;
    cr_asset_code: string;
    cr_qr_code?: string;
    cr_name: string;
    cr_category?: string;
    cr_location_id?: string;
    cr_purchase_date?: string;
    cr_warranty_expiration?: string;
    cr_is_under_warranty?: boolean;
    cr_is_active: boolean;
    cr_notes?: string;
}

export interface KnowledgeArticle {
    cr_knowledge_articleid: string;
    cr_article_id: string;
    cr_title: string;
    cr_category_id: string;
    cr_content: string;
    cr_keywords?: string;
    cr_view_count: number;
    cr_is_published: boolean;
    cr_created_by_user: string;
    createdon: string;
}

export interface SurveyResponse {
    cr_survey_responseid: string;
    cr_survey_id: string;
    cr_ticket_id: string;
    cr_respondent: string;
    cr_satisfaction_rating: SatisfactionRating;
    cr_resolution_quality: SatisfactionRating;
    cr_technician_professionalism: SatisfactionRating;
    cr_comments?: string;
    createdon: string;
    cr_average_rating?: number;
}

// ─── Context Types ──────────────────────────────────────────

export interface AppUser {
    fullName: string;
    objectId: string;
    tenantId: string;
    userPrincipalName: string;
}

// ─── Utility Types ──────────────────────────────────────────

/** Fields required to create a new Ticket */
export type CreateTicketPayload = Pick<
    Ticket,
    | "cr_title"
    | "cr_description"
    | "cr_requesting_department"
    | "cr_requesting_user"
    | "cr_location_id"
    | "cr_category_id"
    | "cr_priority"
    | "cr_is_emergency"
> &
    Partial<Pick<Ticket, "cr_subcategory_id" | "cr_related_asset_id">>;

/** Fields required to create a new Work Order */
export type CreateWorkOrderPayload = Pick<
    WorkOrder,
    "cr_ticket_id" | "cr_assigned_technician"
> &
    Partial<
        Pick<
            WorkOrder,
            | "cr_preliminary_diagnosis"
            | "cr_estimated_labor_hours"
            | "cr_estimated_material_cost"
            | "cr_estimated_external_cost"
        >
    >;

/** Fields required to create a new Material Request */
export type CreateMaterialRequestPayload = Pick<
    MaterialRequest,
    | "cr_ticket_id"
    | "cr_requested_by"
    | "cr_material_description"
    | "cr_estimated_cost"
    | "cr_justification"
> &
    Partial<Pick<MaterialRequest, "cr_workorder_id">>;

/** Fields required to submit a survey */
export type CreateSurveyPayload = Pick<
    SurveyResponse,
    | "cr_ticket_id"
    | "cr_respondent"
    | "cr_satisfaction_rating"
    | "cr_resolution_quality"
    | "cr_technician_professionalism"
> &
    Partial<Pick<SurveyResponse, "cr_comments">>;
